language: node_js
# nodejs版本
node_js: 8.6.0

# Travis-CI Caching
cache:
    apt: true
    directories:
        - node_modules

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

# S: Build Lifecycle
install:
  - npm install

before_script:

script:
  - hexo clean  #清除
  - hexo g

after_script:
  - mv .circleci ./public
  - cd ./public
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Travis CI Auto Builder Docs at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
# E: Build LifeCycle

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
env:
 global:
   # 我将其添加到了travis-ci的环境变量中
   #- GH_REF: github.com/yimogit/metools.git 

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - xiove@qq.com
  on_success: change
  on_failure: always