version: 2
jobs:
  build:
    branches:
      only:
        - master
        - dev
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:8.4.0
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test